### ISSUE TITLE
Peer Review 1(by Yingke He)

### ISSUE THREAD

**Issue by ohyykk** [DianaShen1224/Relationship-between-infant-mortality-rate-and-prohibited-abortion#1]
**Summary**
This paper examines the impact of abortion bans following the Dobbs decision on infant mortality rates in the United States using a Difference-in-Differences (DID) approach. The study finds that states enforcing abortion bans experienced increased infant mortality rates. Key findings highlight significant demographic disparities, with Black mothers facing disproportionately higher rates. The paper emphasizes the compounded effects of policy changes and demographic factors on public health.

**Strong positive points:**
The use of a  Difference-in-Differences model provides strong causal inference for evaluating policy impacts.
The paper effectively integrates demographic variables to offer a detailed explanation of demographic factors on mortality rates.
The discussion on racial and socioeconomic inequities is clear, underscoring the public health implications of restrictive abortion laws. Appendix also provides questionnaires. 

**Critical improvements needed:**
- Parallel Trends Assumption: The manuscript briefly mentions the parallel trends assumption but does not provide a graphical or statistical validation. Adding pre-intervention trend comparisons would enhance the credibility of the DID model.
- Temporal Data Limitations: The study acknowledges the 2021–2022 timeframe but does not fully address how this limitation impacts the generalizability of its findings. Extending the data to include 2023 or later would strengthen conclusions.
- Confounding Variables: While the model includes controls like maternal age and race, it overlooks potential confounders such as healthcare infrastructure variability and socioeconomic factors. Addressing these could refine the analysis.
- Figure Interpretations: Some figures lack detailed captions and explanations, making it difficult to interpret key results without referencing the main text. Clearer annotations would improve accessibility.

**Suggestions for improvement:**
Include a supplementary figure or table validating the parallel trends assumption.
Expand the discussion on limitations to explicitly consider how healthcare access and state-level policies may confound the observed effects.
Incorporate more comprehensive sensitivity analyses to test the robustness of the DID estimates.
Simplify technical jargon in the discussion section to ensure accessibility for a broader audience.
Enhance the quality of visualizations, particularly Figures 2 and 3, with consistent formatting and more descriptive captions.
Provide a summary table of key demographic findings to reinforce the manuscript's emphasis on disparities.

**Evaluation:**
R/Python cited (1/1 pts): Clear documentation of R packages used.
Data cited (1/1 pts): Data sources are adequately cited (CDC WONDER).
Class paper (1/1 pts): Well-suited for academic presentation.
LLM documentation (1/1 pts): Not applicable.
Title (2/2 pts): Informative and concise.
Author, date, and repo (2/2 pts): Properly included.
Abstract (4/4 pts): Provides a clear and detailed summary of the study.
Introduction (4/4 pts): Engaging and contextualizes the study effectively.
Estimand (1/1 pts): Clearly defined.
Data (9/10 pts): Comprehensive but lacks granularity in capturing intra-state disparities.
Measurement (4/4 pts): clear and well organized.
Model (8/10 pts): Well-designed but requires further validation for assumptions.
Results (9/10 pts): Detailed but could benefit from extended data analysis.
Discussion (10/10 pts): Thorough and reflective.
Prose (5/6 pts): Effective but occasionally dense with technical terms.
Cross-references (1/1 pts): Appropriately linked.
Captions (1/2 pts): Could be more descriptive.
Graphs/tables/etc (3/4 pts): Visually effective but inconsistent formatting.
Surveys, sampling, and observational data appendix (9/10 pts): Comprehensive but slightly redundant.
Referencing (4/4 pts): Comprehensive and accurate.
Commits (0/2 pts): Needs to be more detailed
Sketches (0/2 pts): Sketches not found
Simulation (3/4 pts): Bayesian framework is appropriate and well-documented.
Tests (3/4 pts): Thorough diagnostic checks.
Parquet (1/1 pts): Efficient use of data management tools.
Reproducible workflow (4/4 pts): Exemplary documentation of methods.
Enhancements (3/4 pts): Strong overall but could expand demographic granularity.
Miscellaneous (0/3 pts): Supplementary materials needs to be updated
Estimated overall mark:
84 out of 100.

**Any other comments:**
This paper is well organized overall. Though still needs some refinements, particularly in validating methodological assumptions and extending data coverage.

**Comment by DianaShen1224** [comment]
Thank you for the detailed feedback. I have simplified the title and revised the abstract to include key findings and implications. The introduction now provides more context on prior research and highlights the paper’s contributions earlier. Descriptive statistics for key variables (e.g., maternal age, race, infant mortality) have been added, and assumptions of the DID model are validated with graphical and statistical checks. The Bayesian model presentation has been simplified for clarity, and the discussion elaborates on long-term implications and public health interventions. Additionally, I clarified how qualitative survey results complement the analysis and improved reproducibility using structured workflows and enhanced tests. Future work includes integrating a simulation section and refining the survey for better alignment.
